// Copyright (c) 2025-2026 Abderaouf Bouzerara
// SPDX-License-Identifier: MIT

export const POSTGRES_INVENTORY_REPOSITORY = Symbol(
  'POSTGRES_INVENTORY_REPOSITORY',
);
export const CACHED_INVENTORY_REPOSITORY = Symbol(
  'CACHED_INVENTORY_REPOSITORY',
);
export const POSTGRES_RESERVATION_REPOSITORY = Symbol(
  'POSTGRES_RESERVATION_REPOSITORY',
);
