export const POSTGRES_INVENTORY_REPOSITORY = Symbol(
  'POSTGRES_INVENTORY_REPOSITORY',
);
export const CACHED_INVENTORY_REPOSITORY = Symbol(
  'CACHED_INVENTORY_REPOSITORY',
);
export const POSTGRES_RESERVATION_REPOSITORY = Symbol(
  'POSTGRES_RESERVATION_REPOSITORY',
);
