export const POSTGRES_ORDER_REPOSITORY = Symbol('POSTGRES_ORDER_REPOSITORY');
export const REDIS_ORDER_REPOSITORY = Symbol('REDIS_ORDER_REPOSITORY');
export const CUSTOMER_GATEWAY = Symbol('CUSTOMER_GATEWAY');
export const CART_GATEWAY = Symbol('CART_GATEWAY');
export const INVENTORY_RESERVATION_GATEWAY = Symbol(
  'INVENTORY_RESERVATION_GATEWAY',
);
export const PAYMENT_GATEWAY = Symbol('PAYMENT_GATEWAY');
