image: node:24

options:
  max-time: 20
  size: 2x

pipelines:
  branches:
    master:
      - step:
          name: Install & Test (Master branch)
          caches:
            - node
          script:
            - echo "🛠 Installing dependencies (legacy peer deps to avoid conflicts)..."
            - npm ci --legacy-peer-deps
            - echo "🧪 Running tests..."
            - npm run test:ci
          artifacts:
            - coverage/**
definitions:
  caches:
    node: ~/.npm
