export const POSTGRES_USER_REPOSITORY = Symbol('POSTGRES_USER_REPOSITORY');
export const CACHED_USER_REPOSITORY = Symbol('CACHED_USER_REPOSITORY');
export const CUSTOMER_GATEWAY = Symbol('CUSTOMER_GATEWAY');
