export const POSTGRES_PRODUCT_REPOSITORY = Symbol(
  'POSTGRES_PRODUCT_REPOSITORY',
);
export const CACHED_PRODUCT_REPOSITORY = Symbol('CACHED_PRODUCT_REPOSITORY');
export const POSTGRES_CATEGORY_REPOSITORY = Symbol(
  'POSTGRES_CATEGORY_REPOSITORY',
);
export const CURRENCY_CONFIG_PORT = Symbol('CURRENCY_CONFIG_PORT');
