// Copyright (c) 2025-2026 Abderaouf Bouzerara
// SPDX-License-Identifier: AGPL-3.0-only

export const POSTGRES_PRODUCT_REPOSITORY = Symbol(
  'POSTGRES_PRODUCT_REPOSITORY',
);
export const CACHED_PRODUCT_REPOSITORY = Symbol('CACHED_PRODUCT_REPOSITORY');
export const POSTGRES_CATEGORY_REPOSITORY = Symbol(
  'POSTGRES_CATEGORY_REPOSITORY',
);
