/** Stable codes clients can branch on. The value is the wire string. */
export const ErrorCode = {
  DOMAIN_ERROR: 'DOMAIN_ERROR',
  USECASE_ERROR: 'USECASE_ERROR',
  SERVICE_ERROR: 'SERVICE_ERROR',
  REPOSITORY_ERROR: 'REPOSITORY_ERROR',
  INFRASTRUCTURE_ERROR: 'INFRASTRUCTURE_ERROR',
  QUERY_ERROR: 'QUERY_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  OPTIMISTIC_LOCK_CONFLICT: 'OPTIMISTIC_LOCK_CONFLICT',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  CHECKOUT_ACCOUNT_REQUIRED: 'CHECKOUT_ACCOUNT_REQUIRED',
  CART_EMPTY: 'CART_EMPTY',
  SHIPPING_ADDRESS_REQUIRED: 'SHIPPING_ADDRESS_REQUIRED',
  REFUND_AMOUNT_INVALID: 'REFUND_AMOUNT_INVALID',
  AMOUNT_INVALID: 'AMOUNT_INVALID',
  CURRENCY_INVALID: 'CURRENCY_INVALID',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  QUANTITY_INVALID: 'QUANTITY_INVALID',
  PAYMENT_PROVIDER_MISMATCH: 'PAYMENT_PROVIDER_MISMATCH',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
