import { NestFactory } from '@nestjs/core';
import { AppModule } from '../src/app.module';
import { UserRepository } from '../src/modules/auth/core/domain/repositories/user.repository';
import { RoleRepository } from '../src/modules/auth/core/domain/repositories/role.repository';
import { PasswordHasher } from '../src/shared-kernel/domain/interfaces/password-hasher.interface';
import { SystemRoleCode } from '../src/modules/auth/core/domain/reference-data/system-roles';
import { User } from '../src/modules/auth/core/domain/entities/user';
import * as readline from 'readline';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const question = (query: string): Promise<string> =>
  new Promise((resolve) => rl.question(query, resolve));

const maskEmail = (email: string): string => {
  if (!email.includes('@')) return '***';
  const [local, domain] = email.split('@');
  if (local.length <= 1) return `***@${domain}`;
  return `${local[0]}***@${domain}`;
};

const hiddenQuestion = (query: string): Promise<string> =>
  new Promise((resolve, reject) => {
    const stdin = process.stdin;
    const stdout = process.stdout;

    stdout.write(query);

    stdin.resume();
    stdin.setRawMode(true);

    let input = '';
    const listener = (chunk: Buffer) => {
      const char = chunk.toString();

      switch (char) {
        case '\n':
        case '\r':
        case '\u0004': // End of transmission
          stdin.setRawMode(false);
          stdin.pause();
          stdin.removeListener('data', listener);
          stdout.write('\n');
          resolve(input);
          break;
        case '\u0003': // Ctrl+C
          stdin.setRawMode(false);
          stdin.pause();
          stdin.removeListener('data', listener);
          reject(new Error('User cancelled the operation'));
          break;
        case '\u0008': // Backspace
        case '\u007f':
          if (input.length > 0) {
            input = input.slice(0, -1);
            stdout.write('\b \b');
          }
          break;
        default:
          input += char;
          stdout.write('*');
          break;
      }
    };

    stdin.on('data', listener);
  });

async function bootstrap() {
  let app:
    | Awaited<ReturnType<typeof NestFactory.createApplicationContext>>
    | undefined;

  try {
    app = await NestFactory.createApplicationContext(AppModule);

    const userRepository = app.get(UserRepository);
    const roleRepository = app.get(RoleRepository);
    const passwordHasher = app.get(PasswordHasher);

    console.log('\n--- E-Commerce Admin Bootstrap ---');

    const email = await question('Enter admin email: ');
    const password = await hiddenQuestion(
      'Enter admin password (min 6 chars): ',
    );

    if (password.length < 6) {
      console.error('Password must be at least 6 characters long.');
      process.exitCode = 1;
      return;
    }

    const existing = await userRepository.findByEmail(email);

    if (existing.isFailure) {
      console.error(
        '\n❌ Failed to check existing admin user:',
        existing.error.message,
      );
      process.exitCode = 1;
      return;
    }

    if (existing.value !== null) {
      console.log(`User with email ${maskEmail(email)} already exists.`);
      return;
    }

    const roleResult = await roleRepository.findByCode(
      SystemRoleCode.SUPER_ADMIN,
    );
    if (roleResult.isFailure || !roleResult.value) {
      console.error(
        'SUPER_ADMIN role not found. Please ensure initializers have run.',
      );
      process.exitCode = 1;
      return;
    }

    const passwordHash = await passwordHasher.hash(password);

    const user = User.create(
      null, // ID generated by DB
      email,
      passwordHash,
      true, // mustChangePassword forces password change on first login
      roleResult.value.id,
      undefined, // customerId
    );

    const saveResult = await userRepository.save(user);

    if (saveResult.isSuccess) {
      console.log(`\n✅ Super admin seeded successfully: ${maskEmail(email)}`);
      console.log(`Note: You must change your password on first login.\n`);
    } else {
      console.error(
        '\n❌ Failed to seed super admin',
        saveResult.error.message,
      );
      process.exitCode = 1;
    }
  } catch (error) {
    console.error('\n❌ Unexpected error during admin seeding:', error);
    process.exitCode = 1;
  } finally {
    rl.close();
    if (app) await app.close();
  }
}

bootstrap();
