export const POSTGRES_CART_REPOSITORY = Symbol('POSTGRES_CART_REPOSITORY');
export const REDIS_CART_REPOSITORY = Symbol('REDIS_CART_REPOSITORY');
export const INVENTORY_GATEWAY = Symbol('INVENTORY_GATEWAY');
