export const POSTGRES_CART_REPOSITORY = Symbol('POSTGRES_CART_REPOSITORY');
export const CACHED_CART_REPOSITORY = Symbol('CACHED_CART_REPOSITORY');
export const INVENTORY_GATEWAY = Symbol('INVENTORY_GATEWAY');
export const PRODUCT_GATEWAY = Symbol('PRODUCT_GATEWAY');
