import { Result } from '../../../../../shared-kernel/domain/result';
import { DomainError } from '../../../../../shared-kernel/domain/exceptions/domain.error';
import { ErrorFactory } from '../../../../../shared-kernel/domain/exceptions/error.factory';
import { IUser } from '../interfaces/user.interface';
import { IAddress } from '../interfaces/address.interface';
import { Address, AddressProps, UpdateAddressProps } from './address';

export interface UserProps {
  id: number | null;
  firstName: string;
  lastName: string;
  email: string;
  phone: string | null;
  isActive: boolean;
  addresses: AddressProps[];
  createdAt: Date | null;
  updatedAt: Date | null;
}

export class User implements IUser {
  private readonly _id: number | null;
  private _firstName: string;
  private _lastName: string;
  private _email: string;
  private _phone: string | null;
  private _isActive: boolean;
  private _addresses: Address[];
  private readonly _createdAt: Date;
  private _updatedAt: Date;

  constructor(props: UserProps) {
    const validationResult = this.validateProps(props);
    if (validationResult.isFailure) throw validationResult.error;

    this._id = props.id ?? null;
    this._firstName = props.firstName.trim();
    this._lastName = props.lastName.trim();
    this._email = props.email.trim().toLowerCase();
    this._phone = props.phone;
    this._isActive = props.isActive;
    this._addresses =
      props.addresses.map((addr) => Address.fromProps(addr)) || [];
    this._createdAt = props.createdAt || new Date();
    this._updatedAt = props.updatedAt || new Date();
  }

  private validateProps(props: UserProps): Result<void, DomainError> {
    // ID validation removed - auto-generated by database
    if (!props.email?.trim()) {
      return ErrorFactory.DomainError('Email is required');
    }
    if (!this.isValidEmail(props.email)) {
      return ErrorFactory.DomainError('Invalid email format');
    }

    return Result.success(undefined);
  }

  private isValidEmail(email: string): boolean {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  }

  // Getters
  get id(): number | null {
    return this._id;
  }
  get firstName(): string {
    return this._firstName;
  }
  get lastName(): string {
    return this._lastName;
  }

  get email(): string {
    return this._email;
  }

  get phone(): string | null {
    return this._phone;
  }

  get addresses(): IAddress[] {
    return this._addresses;
  }

  get isActive(): boolean {
    return this._isActive;
  }

  get createdAt(): Date {
    return new Date(this._createdAt);
  }

  get updatedAt(): Date {
    return new Date(this._updatedAt);
  }

  // Business Logic
  addAddress(addressProps: AddressProps): Result<void, DomainError> {
    const isAddressExist = this.addresses?.some(
      (addr) => addr.street === addressProps.street,
    );
    if (isAddressExist)
      return ErrorFactory.DomainError('Address already exist');

    const address = Address.create({
      id: null,
      userId: this._id!,
      street: addressProps.street,
      city: addressProps.city,
      state: addressProps.state,
      postalCode: addressProps.postalCode,
      country: addressProps.country,
      type: addressProps.type,
      street2: addressProps.street2,
      deliveryInstructions: addressProps.deliveryInstructions,
      isDefault: addressProps.isDefault,
      createdAt: null,
      updatedAt: null,
    });

    this._addresses.push(address);
    this._updatedAt = new Date();
    return Result.success(undefined);
  }

  updatePersonalInfo(
    firstName: string,
    lastName: string,
    email: string,
    phone: string | null,
  ): Result<void, DomainError> {
    const validationResult = this.validateProps({
      id: this._id,
      firstName,
      lastName,
      email,
      phone,
      isActive: this._isActive,
      addresses: this._addresses,
      createdAt: this._createdAt,
      updatedAt: this._updatedAt,
    });
    if (validationResult.isFailure) return validationResult;

    this._firstName = firstName.trim();
    this._lastName = lastName.trim();
    this._email = email.trim().toLowerCase();
    this._phone = phone;
    this._updatedAt = new Date();
    return Result.success(undefined);
  }

  setDefaultAddress(addressId: number): Result<void, DomainError> {
    const address = this._addresses.find((address) => address.id === addressId);
    if (!address) {
      return ErrorFactory.DomainError(`Address with ID ${addressId} not found`);
    }
    this._addresses.forEach((addr) => {
      if (addr.id !== addressId) addr.unsetAsDefault();
    });
    address.setAsDefault();

    this._updatedAt = new Date();
    return Result.success(undefined);
  }

  updateAddress(
    addressId: number,
    addressProps: UpdateAddressProps,
  ): Result<void, DomainError> {
    const address = this._addresses.find((address) => address.id === addressId);

    if (!address) {
      return ErrorFactory.DomainError(`Address with id ${addressId} not found`);
    }

    const updateResult = address.updateAddress({
      street: addressProps.street,
      city: addressProps.city,
      state: addressProps.state,
      postalCode: addressProps.postalCode,
      country: addressProps.country,
      street2: addressProps.street2,
      type: addressProps.type,
      deliveryInstructions: addressProps.deliveryInstructions,
    });

    if (updateResult.isFailure) return updateResult;

    this._updatedAt = new Date();
    return Result.success(undefined);
  }

  deleteAddress(addressId: number): Result<void, DomainError> {
    const address = this._addresses.find((address) => address.id === addressId);
    if (!address) {
      return ErrorFactory.DomainError(`Address with ID ${addressId} not found`);
    }

    this._addresses = this._addresses.filter((addr) => addr.id !== addressId);

    this._updatedAt = new Date();
    return Result.success(undefined);
  }

  deactivate(): Result<void, DomainError> {
    if (!this._isActive) {
      return ErrorFactory.DomainError('User is already deactivated');
    }
    this._isActive = false;
    this._updatedAt = new Date();
    return Result.success(undefined);
  }

  activate(): Result<void, DomainError> {
    if (this._isActive) {
      return ErrorFactory.DomainError('User is already active');
    }
    this._isActive = true;
    this._updatedAt = new Date();
    return Result.success(undefined);
  }

  // Serialization
  get toProps(): UserProps {
    return {
      id: this._id,
      firstName: this._firstName,
      lastName: this._lastName,
      email: this._email,
      phone: this._phone,
      addresses: this._addresses,
      isActive: this._isActive,
      createdAt: this._createdAt,
      updatedAt: this._updatedAt,
    };
  }

  toPrimitives(): IUser {
    return {
      id: this._id,
      firstName: this._firstName,
      lastName: this._lastName,
      email: this._email,
      phone: this._phone,
      addresses: this._addresses,
      isActive: this._isActive,
      createdAt: this._createdAt,
      updatedAt: this._updatedAt,
    };
  }

  static fromProps(data: UserProps): User {
    const userProps: UserProps = {
      id: data.id,
      firstName: data.firstName,
      lastName: data.lastName,
      email: data.email,
      phone: data.phone,
      addresses: data.addresses,
      isActive: data.isActive,
      createdAt: data.createdAt,
      updatedAt: data.updatedAt,
    };
    return new User(userProps);
  }

  static create(props: UserProps): User {
    return new User({
      id: props.id,
      firstName: props.firstName,
      lastName: props.lastName,
      email: props.email,
      phone: props.phone,
      addresses: props.addresses,
      isActive: props.isActive,
      createdAt: props.createdAt,
      updatedAt: props.updatedAt,
    });
  }
}
